local utils = require "quickfill.utils"

describe("utils", function()
    describe("overlap", function()
        it("should find no overlap", function()
            local a, ol, b = utils.overlap("hello", "world")
            assert.are.same("hello", a)
            assert.are.same("", ol)
            assert.are.same("world", b)
        end)

        it("should find full overlap (b is a continuation of a)", function()
            local a, ol, b = utils.overlap("function ()", "n () local")
            assert.are.same("functio", a)
            assert.are.same("n ()", ol)
            assert.are.same(" local", b)
        end)

        it("should find partial overlap", function()
            local a, ol, b = utils.overlap("local variable", "iable_value = 1")
            assert.are.same("local var", a)
            assert.are.same("iable", ol)
            assert.are.same("_value = 1", b)
        end)

        it("should handle full match (a is a prefix of b)", function()
            local a, ol, b = utils.overlap("local ", "local my_var")
            assert.are.same("", a)
            assert.are.same("local ", ol)
            assert.are.same("my_var", b)
        end)

        it("should handle single character overlap", function()
            local a, ol, b = utils.overlap("barf", "foo")
            assert.are.same("bar", a)
            assert.are.same("f", ol)
            assert.are.same("oo", b)
        end)
    end)
end)
